version: "3.9"

services:
  api:
    &api
    container_name: api
    image: node-api
    init: true
    tty: true
    stdin_open: true
    restart: always

    build: .

    env_file:
      - ./.env

    networks:
      - api-db
      - api-frontend

    depends_on:
      - postgres

    volumes:
      - ./backend:/home/node/code

    ports:
      - 5000:5000

    entrypoint: bash -c ". startup-check.sh && npm run start"
  
  frontend:
    <<: *api
    container_name: frontend

    networks:
      - api-frontend

    env_file: []
    
    depends_on:
      - api
    
    volumes:
      - ./frontend:/home/node/code
    
    ports:
      - 8080:8080
    
    entrypoint: bash -c "npm install && npm run serve"

  shell:
    <<: *api
    container_name: api-shell

    ports:
      - 5000:5000
      - 9229:9229

    profiles:
      - shell

    entrypoint: bash -c ". startup-check.sh; exec bash"

  postgres:
    container_name: postgres
    restart: always
    image: postgres:alpine

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    networks:
      - api-db

    ports:
      - 5432:5432

networks:
  api-db:
  api-frontend:
